name: Code quality checks

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.10', '3.12']
        toxenv: [isort, black, flake8]

    name: "Code style: ${{ matrix.toxenv }}, py${{ matrix.python }}"

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: 'false'
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: pip install tox tox-gh-actions tox-uv

      - run: tox
        env:
          TOXENV: ${{ matrix.toxenv }}
