name: Code quality checks

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.10', '3.12']
        toxenv: [isort, black, flake8]

    name: "Code style: ${{ matrix.toxenv }}, py${{ matrix.python }}"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: pip install tox tox-gh-actions tox-uv

      - run: tox
        env:
          TOXENV: ${{ matrix.toxenv }}
